config/routes.rb
Rails.application.routes.draw do
  resources :holdings

  resources :securities
  resources :transactions, only: [:index, :new, :create]

  root to: "pages#index"

  get 'github_login', to: 'pages#github_login'

  # Used by github for authentication loop
  get 'github_verify', to: 'pages#github_verify'

  namespace :api do
    namespace :v1 do
      namespace :users do
        get 'authenticate'
        get 'verify'
      end
    end
  end

  namespace :stocks do
    get :quote
    get :lookup
  end

  get 'test', to: "pages#test"
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :holdings
  has_many :transactions

  validates :github_id, presence: true
  validates :auth_token, presence: true

  def self.authenticate(auth_token)
    User.find_by_auth_token(auth_token)
  end

  def self.fetch(access_token)
    user_params = user_params(access_token)
    find_or_create(access_token, user_params)
  end

  def self.find_or_create(access_token, user_params)
    user = find_or_create_by(github_id: user_params[:id]) do |user|
      user.name = user_params[:name]
      user.email = user_params[:email]
      user.github_access_token = access_token
      user.auth_token = SecureRandom.urlsafe_base64(nil, false)
    end
    user.valid? ? user : nil
  end

  def self.user_params(access_token)
    github_user = Api::Github.get_user(access_token)
    HashWithIndifferentAccess.new(github_user)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_filter :authenticate

  def authenticate
    session[:local_referer] = "api"
    redirect_to Api::Github.auth_code_url
  end

  def verify
    @user = User.find(params[:user_id])
    render json: {access_token: @user}
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate

  def authenticate
    unless signed_in?
      puts "Unauthenticated User - Please sign in"
      redirect_to root_path, notice: "Please sign in"
    end
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authenticate, only: [:index, :github_login, :github_verify]

  def index
    puts "Params #{params}"
  end

  def test
    put "Testing Authentication"
  end

  def github_login
    redirect_to Api::Github.auth_code_url
  end

  def github_verify
    puts "Verify Params #{params}"
    access_token = Api::Github.get_access_token(params[:code])

    @user = User.fetch(access_token)
    session[:auth_token] = @user.auth_token
    logger.info("session[:local_referer] #{session[:local_referer]}")
    if session[:local_referer] == "api"
      session[:local_referer] = nil
      redirect_to api_v1_users_verify_path(user_id: @user.id)
    else
      session[:local_referer] = nil
      redirect_to root_path
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def quote

  end

  def lookup
    render json: formatted_results(params[:query])
  end

  def formatted_results(query)
    results = Api::Securities.lookup(params[:query])
    results.map{ |r| {value: "#{r["Symbol"]} - #{r["Name"]}"} }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def signed_in?
    if Rails.env.development?
      @user = User.first
      return @user
    end
    auth_token = session[:auth_token]
    @user = User.authenticate(auth_token)
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggle" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <%= link_to "Stock Portfolio", root_path, class:"navbar-brand" %>
      </button>
      <div id="navbar-main" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Portfolio", '#' %></li>
        </ul>
        <form class="navbar-form navbar-right" role="search" action="/stocks/quote">
          <div class="form-group">
            <input class="form-control stock-lookup typeahead" type="text" placeholder="Search">
          </div>
          <input type="submit" class="btn btn-default" value="Submit">
        </form>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <title>Stock Portfolio API</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <div class="container" style="margin-top: 30px;">
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/index.html.erb
<h1>Stock Portfolio API</h1>
<% unless signed_in? %>
  <%= link_to "Log in with Github", github_login_path %>
<% end %>

app/views/pages/test.html.erb
<h1>Welcome, you are in the club</h1>

app/views/stocks/quote.html.erb
<h1>Stock Quote</h1>